// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0E5Bt2hsX8KF2BtG5LteYYxhyrup0Smo',
    appId: '1:931859519492:web:723bf6fb692eca4931bd51',
    messagingSenderId: '931859519492',
    projectId: 'fitmax-186dc',
    authDomain: 'fitmax-186dc.firebaseapp.com',
    storageBucket: 'fitmax-186dc.firebasestorage.app',
    measurementId: 'G-YKX78BJC5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUrg2HblHh31Q--iNRqR7icps_KReKss4',
    appId: '1:931859519492:android:c823db22102a9c1231bd51',
    messagingSenderId: '931859519492',
    projectId: 'fitmax-186dc',
    storageBucket: 'fitmax-186dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABontb1Nnz9UnnOWLMhT7o53fI5fFHOjg',
    appId: '1:931859519492:ios:89134113e1ec428e31bd51',
    messagingSenderId: '931859519492',
    projectId: 'fitmax-186dc',
    storageBucket: 'fitmax-186dc.firebasestorage.app',
    iosBundleId: 'com.example.comercialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABontb1Nnz9UnnOWLMhT7o53fI5fFHOjg',
    appId: '1:931859519492:ios:89134113e1ec428e31bd51',
    messagingSenderId: '931859519492',
    projectId: 'fitmax-186dc',
    storageBucket: 'fitmax-186dc.firebasestorage.app',
    iosBundleId: 'com.example.comercialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0E5Bt2hsX8KF2BtG5LteYYxhyrup0Smo',
    appId: '1:931859519492:web:39a7eefe5e013df831bd51',
    messagingSenderId: '931859519492',
    projectId: 'fitmax-186dc',
    authDomain: 'fitmax-186dc.firebaseapp.com',
    storageBucket: 'fitmax-186dc.firebasestorage.app',
    measurementId: 'G-RBB2RCDLSM',
  );

}